server:
  port: 8080

spring:
  application:
    name: encyclopedia

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 3s
    socket-timeout: 3s
    index:
      auto-create: true

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/encyclopedia?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # 또는 update (DDL 자동 생성 여부)
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html