spring:
  config:
    import: application-secret.yml

  application:
    name: boindang-user

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      p6spy: info   # ? ??? ??? SQL? ??
      org.hibernate.SQL: info  # Hibernate ?? SQL ?? ???
      root: INFO
      com.monthlyzip: DEBUG  # ? ???? ???? ?? DEBUG ?? ??
    charset:
      console: UTF-8
      file: UTF-8

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${HOST_IP}

springdoc:
  swagger-ui:
    path: /user/swagger-ui
  api-docs:
    path: /user/v3/api-docs

server:
  port: 8080
