spring:
  application:
   name: test-service

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.31.4.100:8761/eureka/

server:
  port: 8081

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5p --- %c.%M : %m%n"