spring:
  application:
    name: image-service
  config:
    import: optional:file:.env_image[.properties]
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      maximum-pool-size: 4
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${HOST_IP}

springdoc:
  swagger-ui:
    path: /image/swagger-ui

open-api:
  service:
    url: http://43.203.153.204:8081


# S3
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

## prometheusds
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  server:
#    port: 1111
##    base-path:

server:
  port: 8081
