services:
  user-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kimhwidong/boindang-repo:auth-service
    container_name: auth-service
    environment:
      EUREKA_URL: ${EUREKA_URL}
      HOST_IP: ${HOST_IP}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
      - "1111:1111"
    restart: always
    networks:
      - redis-network

networks:
  redis-network:
    external: true