spring:
  application:
    name: gateway
  config:
    import: optional:file:.env_gateway[.properties]
  cloud:
    gateway:
      routes:
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
        - id: encyclopedia-service
          uri: lb://ENCYCLOPEDIA
          predicates:
            - Path=/encyclopedia/**
        - id: campaign-service
          uri: lb://CAMPAIGN-SERVICE
          predicates:
            - Path=/campaign/**
        - id: ocr-service
          uri: lb://OCR-SERVICE
          predicates:
            - Path=/ocr/**
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /image/v3/api-docs
        name: Image
      - url: /encyclopedia/v3/api-docs
        name: Encyclopedia
      - url: /campaign/v3/api-docs
        name: Campaign

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
