spring:
  application:
    name: gateway
  config:
    import: optional:file:.env_gateway[.properties]
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - StripPrefix=2
        - id: encyclopedia-service
          uri: lb://ENCYCLOPEDIA
          predicates:
            - Path=/encyclopedia/**
          filters:
            - StripPrefix=2
        - id: campaign-service
          uri: lb://CAMPAIGN
          predicates:
            - Path=/campaign/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://BOINDANG-USER
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=2
        - id: auth-service
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=2
        - id: nutrition-service
          uri: lb://NUTRITION-SERVICE
          predicates:
            - Path=/nutrition/**
          filters:
            - StripPrefix=2
        - id: quiz-service
          uri: lb://QUIZ
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=2
        - id: ocr-service
          uri: lb://OCR-SERVICE
          predicates:
            - Path=/ocr/**
          filters:
            - StripPrefix=2

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8000

