spring:
  application:
    name: gateway
  config:
    import: optional:file:.env_gateway[.properties]
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'https://localhost:3000'
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
            exposedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
      routes:
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
            - RewritePath=/image/(?<remaining>.*), /$\{remaining}
        - id: encyclopedia
          uri: lb://ENCYCLOPEDIA
          predicates:
            - Path=/encyclopedia/**
          filters:
            - RewritePath=/encyclopedia/(?<remaining>.*), /$\{remaining}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /image/v3/api-docs
        name: Image
      - url: /encyclopedia/v3/api-docs
        name: Encyclopedia
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG