spring:
  application:
    name: gateway
  config:
    import: optional:file:.env_gateway[.properties]
  cloud:
    gateway:
      routes:
        - id: image-service
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
        - id: encyclopedia
          uri: lb://ENCYCLOPEDIA
          predicates:
            - Path=/encyclopedia/**
          filters:
            - RewritePath=/encyclopedia/(?<segment>.*), /$\{segment}
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL}

springdoc:
  swagger-ui:
    urls[0]:
      name: Encyclopedia API
      url: http://게이트웨이 주소//encyclopedia/v3/api-docs
    urls[1]:
      name: Advisor API
      url: http://게이트웨이 주소/api/advisor/v3/api-docs
    urls[2]:
server:
  port: 8000
