server:
  port: 8082  # nutrition-service 고유 포트

spring:
  application:
    name: nutrition-service
  config:
    import: optional:application-secret.yml

  data:
    mongodb:
      uri: ${DB_URL}
      database: ${DB_NAME}

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${HOST_IP}

springdoc:
  swagger-ui:
    path: /nutrition/swagger-ui
  api-docs:
    path: /nutrition/v3/api-docs

  logging:
    level:
      root: INFO
      com.nutritionservice: DEBUG

#  logging:
#    level:
#      p6spy: info   # ? ??? ??? SQL? ??
#      org.hibernate.SQL: info  # Hibernate ?? SQL ?? ???
#      root: INFO
#      com.monthlyzip: DEBUG  # ? ???? ???? ?? DEBUG ?? ??
#    charset:
#      console: UTF-8
#      file: UTF-8

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher  # Swagger 오류 방지용 (Spring 2.6+)


#user-service:
#  url: http://localhost:8081 # 실제 user-service 주소
#
#feign:
#  client:
#    config:
#      userClient:
#        name: user-service
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
