services:
  gateway-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gateway-server
    container_name: gateway-server
    ports:
      - "8000:8000"
    environment:
      EUREKA_URL: ${EUREKA_URL}
    restart: always
