services:
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kimhwidong/boindang-repo:gateway
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      EUREKA_URL: ${EUREKA_URL}
      JWT_SECRET: ${JWT_SECRET}
    restart: always
