pipeline {
    agent any
    environment {
        DOCKER = 'sudo docker'
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('Build image') {
            steps {
                sh 'ls -al'
                dir('[디렉토리명]) {
                    sh 'ls -al'
                    sh 'chmod +x ./gradlew'
                    sh './gradlew build'
                    sh 'docker build -t [docker hub 계정]/[docker 이미지 이름] .'
                }
                echo 'Build image...'
            }
        }

        stage('Remove Previous image') {
            steps {
                script {
                    try {
                        h 'docker stop [docker 이미지 이름]'
                        sh 'docker rm [docker 이미지 이름]'
                    } catch (e) {
                        echo 'fail to stop and remove container'
                    }
                }
            }
        }
        stage('Run New image') {
            steps {
                sh 'docker run --name [docker hub 계정]/image-service -d -p [포트번호]:[포트번호] [docker hub 계정]/[docker 이미지 이름]'
                echo 'Run New member image'
            }
        }
    }
}
