spring:
  application:
    name: eureka


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # ??? ?? Eureka? ?? ? ?
    fetch-registry: false       # ?? ??? ?? ???? ??
  server:
    wait-time-in-ms-when-sync-empty: 0
