services:
  quiz-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kimhwidong/boindang-repo:quiz-service
    container_name: quiz-service
    environment:
      DB_URL: jdbc:mysql://quiz-db:3308/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8083:8083"
    restart: always
    networks:
      - quiz-network

volumes:
  mysql_data:

networks:
  quiz-network:
    external: true
