spring:
  application:
    name: auth
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expire-time: 600000 # 10min
  refresh-token:
    expire-time: 604800000 # 7day

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${HOST_IP}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 1111

server:
  port: 8080
