spring:
  application:
    name: auth


jwt:
  secret: ${JWT_SECRET}
  access-token:
    expire-time: 259200000 # 3?
  refresh-token:
    expire-time: 604800000 # 7?

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${HOST_IP}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 1111

server:
  port: 8080
