version: "3.8"

services:
  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - redis-network

networks:
  redis-network:
    external: true
